// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package amplify

import (
	"github.com/aws/aws-sdk-go/private/protocol"
)

const (

	// ErrCodeBadRequestException for service response error code
	// "BadRequestException".
	//
	// A request contains unexpected data.
	ErrCodeBadRequestException = "BadRequestException"

	// ErrCodeDependentServiceFailureException for service response error code
	// "DependentServiceFailureException".
	//
	// An operation failed because a dependent service threw an exception.
	ErrCodeDependentServiceFailureException = "DependentServiceFailureException"

	// ErrCodeInternalFailureException for service response error code
	// "InternalFailureException".
	//
	// The service failed to perform an operation due to an internal issue.
	ErrCodeInternalFailureException = "InternalFailureException"

	// ErrCodeLimitExceededException for service response error code
	// "LimitExceededException".
	//
	// A resource could not be created because service quotas were exceeded.
	ErrCodeLimitExceededException = "LimitExceededException"

	// ErrCodeNotFoundException for service response error code
	// "NotFoundException".
	//
	// An entity was not found during an operation.
	ErrCodeNotFoundException = "NotFoundException"

	// ErrCodeResourceNotFoundException for service response error code
	// "ResourceNotFoundException".
	//
	// An operation failed due to a non-existent resource.
	ErrCodeResourceNotFoundException = "ResourceNotFoundException"

	// ErrCodeUnauthorizedException for service response error code
	// "UnauthorizedException".
	//
	// An operation failed due to a lack of access.
	ErrCodeUnauthorizedException = "UnauthorizedException"
)

var exceptionFromCode = map[string]func(protocol.ResponseMetadata) error{
	"BadRequestException":              newErrorBadRequestException,
	"DependentServiceFailureException": newErrorDependentServiceFailureException,
	"InternalFailureException":         newErrorInternalFailureException,
	"LimitExceededException":           newErrorLimitExceededException,
	"NotFoundException":                newErrorNotFoundException,
	"ResourceNotFoundException":        newErrorResourceNotFoundException,
	"UnauthorizedException":            newErrorUnauthorizedException,
}
